classDiagram
    class Car{
        +registration_number
        +year: int
        +licensenumber: string
        +moveForward()
        +moveBackward()
        +stop()
        +turnRight()
        +turnLeft()
    }
    class Wheel{
        +diameter: float
    }
    class Brake{
        +type: string
        +apply()
    }
    class Body{
        +no_of_doors: int
    }
    class Engine{
        +capacity: float
        +number-of-cylinders: int
        +start()
        +brake()
        +accelerate()
    }

    Car "1" -- "1" Engine
    Car "1" -- "1" Body
    Car "1" -- "1" Brake
    Wheel "1" -- "1" Brake
